### ISSUE TITLE
MzTab column encoding

### ISSUE THREAD

**Issue by timosachsenberg** [genericworkflownodes/de.openms.knime#10]
Hi,
I found some issues when looking at the peptide (PEP) section after the import by MzTabReader.
- retention_time is a string but should be a double
- mass_to_charge is a string but should be a double
- peptide_abundance* is a string but should be a double, if it is "null" it should be NA in KNIME
- unique should be a bool type

**Comment by jpfeuffer** [comment]
I am fixing it right now.

**Comment by jpfeuffer** [comment]
Please check.

**Comment by jpfeuffer** [comment]
Remaining problems:
1) Should we keep "null" in String columns or make it MissingType?
2) Sometimes (protein section) no modifications are encoded as "0". Sometimes (peptide or PSM) as "null". Is this in the specification?
Both are not so urgent because they are String Columns anyways.

**Comment by timosachsenberg** [comment]
null is the missing type in mzTab so I would try to get rid of all null and use the KNIME missing type

**Comment by timosachsenberg** [comment]
Reporting of modifications in columns of the protein, peptide and PSM sections:
Fixed modifications or modifications specified as quantification_modification in the metadata Section SHOULD NOT be reported in protein (PRT) and peptide rows (PEP). In contrast, all variable modifications plus fixed modifications like those induced by the quantification reagents MUST be reported in peptide spectrum match rows (PSM).

Modifications or substitutions are modelled using a specific modification object with the following format: 

{position}{parameter}-[{modification or substitution identifier}|{neutral loss}]
The number of modification (or substitution) objects MUST correspond to the number of identified modifications (or substitutions) on a given peptide or PSM. It is also expected that modifications SHOULD be reported for proteins using the same format. However, it is recognised that some export software may not be able to do this. If software cannot determine protein-level modifications, “null” MUST be used. If the software has determined that there are no modifications to a given protein “0” MUST be used. 


So this seems to be correct and only used for proteins

**Comment by timosachsenberg** [comment]
Question is only if we export a 0 correctly or null would be more appropriate.  Can't recall right now if mods are already aggregated from all peptides or if this code is missing in MzTabExporter
