### ISSUE TITLE
Failed to find matching binary

### ISSUE THREAD

**Issue by EAD1994** [genericworkflownodes/de.openms.knime#34]
Hello,

I am a new user of KNIME and I had an issue that I was hoping somebody could help me resolve.

When I connect the Input File node to the FileInfo node and the FileInfo node to the Output Folder node, there is an exclamation mark on the FileInfo node that says that says" Couldn't find a binary file for the executable FileInfo" and it also says "Failed to find matching binary." 

Any tips on how to resolve this issue would be greatly appreciated.

Thank you for your time.

**Comment by EAD1994** [comment]
Hi,

The OS is Windows and 64 bit. I am using KMIME version 3.7.2 and the update site thAT i used to install OpenMS was https://abibuilder.informatik.uni-tuebingen.de/archive/openms/knime-plugin/updateSite/nightly/.

Thank You

**Comment by jpfeuffer** [comment]
Ah indeed. We recently added new dependencies which caused problems on Windows. It might take some days to fix the builds.
For newcomers and everyone that does not need cutting-edge functionality, we recommend the stable update site anyway: http://update.knime.com/community-contributions/trusted/3.7

Thanks for reporting.

**Comment by EAD1994** [comment]
Hi,

Using that new link seems to have worked. Thank you again for the support. Have a great day
