### ISSUE TITLE
OMSSAAadapter not working

### ISSUE THREAD

**Issue by EAD1994** [genericworkflownodes/de.openms.knime#35]
Hello,

I have been having some issues when trying to execute the OMSSAAadapter node in my KNIME workflow. When I try to run it, I get the following message: 

ERROR OMSSAAdapter         0:4        Failing process stdout: [Progress of 'loading spectra list':, , -- done [took 0.39 s (CPU), 0.39 s (Wall)] -- , Progress of 'loading chromatogram list':, , -- done [took 0.00 s (CPU), 0.00 s (Wall)] -- , Chunk size is <=0; disabling chunking of input! If OMSSA crashes due to memory allocation errors, try setting 'chunk_size' to a value below 30000 (e.g., 10000 is usually ok)., Progress of 'OMSSA search':, Error: OMSSA problem! See above for OMSSA error. If this does not help, increase 'debug' level and run again., Note: This message can also be triggered if you run out of space in your tmp directory or (32bit OMSSA only) OMSSA ran out of RAM because chunking was not used (that's the default) or 'chunk_size' was too large (>30k). Look above!, OMSSAAdapter took 1.59 s (wall), 1.45 s (CPU), 0.11 s (system), 1.34 s (user).]
ERROR OMSSAAdapter         0:4        Failing process stderr: [USAGE,   omssacl.exe [-h] [-help] [-xmlhelp] [-pm param] [-d blastdb] [-umm],     [-f infile] [-fx xmlinfile] [-fb dtainfile] [-fp pklinfile],     [-fm pklinfile] [-foms omsinfile] [-fomx omxinfile] [-fbz2 bz2infile],     [-fxml omxinfile] [-o textasnoutfile] [-ob binaryasnoutfile],     [-ox xmloutfile] [-obz2 bz2outfile] [-op pepxmloutfile] [-oc csvfile] [-w],     [-to pretol] [-te protol] [-tom promass] [-tem premass] [-tez prozdep],     [-ti isotopes] [-teppm] [-ta autotol] [-tex exact] [-i ions] [-cl cutlo],     [-ch cuthi] [-ci cutinc] [-cp precursorcull] [-v cleave] [-x taxid],     [-w1 window1] [-w2 window2] [-h1 hit1] [-h2 hit2] [-hl hitlist],     [-hc hitcount] [-ht tophitnum] [-hm minhit] [-hs minspectra] [-he evalcut],     [-mf fixedmod] [-mv variablemod] [-mnm] [-mm maxmod] [-e enzyme],     [-zh maxcharge] [-zl mincharge] [-zoh maxprodcharge] [-zt chargethresh],     [-z1 plusone] [-zc calcplusone] [-zcc calccharge] [-zn negions],     [-pc pseudocount] [-sb1 searchb1] [-sct searchcterm] [-sp productnum],     [-scorr corrscore] [-scorp corrprob] [-no minno] [-nox maxno],     [-is subsetthresh] [-ir replacethresh] [-ii iterativethresh],     [-p prolineruleions] [-il] [-el] [-ml] [-mx modinputfile],     [-mux usermodinputfile] [-nt numthreads] [-ni] [-ns] [-os] [-nrs],     [-logfile File_Name] [-conffile File_Name] [-version] [-version-full],     [-dryrun], , DESCRIPTION,    Search engine for identifying MS/MS peptide spectra, , Use '-help' to print detailed descriptions of command line arguments, ========================================================================, Error: (106.18) , NCBI C++ Exception:,     Error: (CArgException::eSynopsis) Too many positional arguments (1), the offending value: De,     Error: (CArgException::eSynopsis) Application's initialization failed, ]
ERROR OMSSAAdapter         0:4        Execute failed: Failed to execute node OMSSAAdapter

I have tried some of the suggestions that the console gives me such as reducing the chunk size and increasing the debugging level but none of these seem to work. Any suggestions would be appreciated. Thank you for your time.

Ed

**Comment by jpfeuffer** [comment]
Hi!
Yes indeed it seems to be unrelated to chunking. We just put that as a suggestion because it is a common error.
Your error is the following:
`Too many positional arguments (1), the offending value: De`
Do you have any parameter (modification or input file) that has a "De" and some whitespace after that?

**Comment by EAD1994** [comment]
Hello,

I don't believe so. I am using the files that I downloaded for the openMS tutorial. As for any parameters on OMSSAAadapter, none of them seem to have a "De" with whitespace after it. I should note also that I have no problem running the node on my laptop, but for some reason, it doesn't run on my work computer.

Thank You,

Ed

**Comment by jpfeuffer** [comment]
Hi,

hmm.. if you are on Windows, what about your User name? KNIME passes filepaths to temporary files (which are in a subfolder of your User directory usually) to the tools. Maybe it chokes on of of these?

Trying to find the reason first, then we can think about solutions ;)
