### ISSUE TITLE
remove legacy branch kime 2.9

### ISSUE THREAD

**Issue by timosachsenberg** [genericworkflownodes/de.openms.knime#4]

**Comment by timosachsenberg** [comment]
removed

**Comment by aiche** [comment]
I assume that the 2.9 line was removed from the builds as well, otherwise the build will point to the now missing branch

**Comment by timosachsenberg** [comment]
I talked about this with Julianus - he removes the build. We saw no need to support it any longer as the KNIME guys only provide support down to  2.10 (with 2.12 being the current version)

**Comment by jpfeuffer** [comment]
Yes, the build scripts still support it but the builds for 2.9 are not scheduled anymore. Any objections?
